In [1]:
# from keras.models import Model
# from keras.layers import Input, LSTM
# from keras.layers import LSTM
# from numpy import array
import tensorflow as tf
import numpy as np

In [2]:
# define model
inputs1 = tf.keras.layers.Input(shape=(3, 1))
lstm1, state_h, state_c = tf.keras.layers.LSTM(1, return_state=True)(inputs1)
model = tf.keras.models.Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
# define input data
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

1/1 [==============================] - 1s 561ms/step
[array([[-0.07213721]], dtype=float32), array([[-0.07213721]], dtype=float32), array([[-0.1585154]], dtype=float32)]


In [3]:
model.layers[1].trainable_weights

[<tf.Variable 'lstm/lstm_cell/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.67609894,  0.966764  , -0.6084736 , -0.6098552 ]],
       dtype=float32)>,
 <tf.Variable 'lstm/lstm_cell/recurrent_kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[-0.4943285 ,  0.6291633 , -0.3968252 , -0.44980264]],
       dtype=float32)>,
 <tf.Variable 'lstm/lstm_cell/bias:0' shape=(4,) dtype=float32, numpy=array([0., 1., 0., 0.], dtype=float32)>]

In [4]:
# example inputs
inputs = tf.convert_to_tensor(np.random.rand(3, 4), dtype='float32')  # 3 timesteps, 4 features
h_c = [tf.zeros((1,2)),  tf.zeros((1,2))]  # must initialize hidden/cell state for lstm cell
h_c = tf.convert_to_tensor(h_c, dtype='float32')
lstm = tf.keras.layers.LSTMCell(2)

# example of how you accumulate cell state over repeated calls to LSTMCell
inputs = tf.unstack(inputs, axis=0)
c_states = []
for cur_inputs in inputs:
    out, h_c = lstm(tf.expand_dims(cur_inputs, axis=0), h_c)
    h, c = h_c
    c_states.append(c)

In [5]:
inputs

[<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.7180736 , 0.48780382, 0.04530875, 0.47551927], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.25782806, 0.83554184, 0.5481133 , 0.31035987], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.26304522, 0.6458942 , 0.33818477, 0.96949106], dtype=float32)>]

In [6]:
c_states

[<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.07483758, -0.10022224]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 0.03573794, -0.09314883]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.27337018, 0.01560613]], dtype=float32)>]

In [7]:
h_c

[<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.12335735, 0.00852051]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.27337018, 0.01560613]], dtype=float32)>]

In [8]:
out

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.12335735, 0.00852051]], dtype=float32)>

In [9]:
lstm.weights

[<tf.Variable 'lstm_cell_1/kernel:0' shape=(4, 8) dtype=float32, numpy=
 array([[-0.4129961 , -0.23077962, -0.4612519 , -0.4777711 , -0.6693022 ,
         -0.20505589,  0.22649378,  0.44638318],
        [ 0.6177483 ,  0.43389827,  0.20113486,  0.6652555 ,  0.02240342,
         -0.46221572,  0.49044484, -0.57461375],
        [ 0.08268219, -0.40224227,  0.16182536,  0.10629606,  0.2234919 ,
          0.5602791 , -0.04792315, -0.6079809 ],
        [-0.24933231,  0.26024413, -0.46070164,  0.03598028,  0.6305291 ,
          0.33388525, -0.51943195,  0.68575984]], dtype=float32)>,
 <tf.Variable 'lstm_cell_1/recurrent_kernel:0' shape=(2, 8) dtype=float32, numpy=
 array([[-0.24514997, -0.05457464,  0.50400734,  0.29810792,  0.28932017,
         -0.22981718,  0.63234675, -0.24009763],
        [ 0.48811132, -0.26110968, -0.01321633, -0.4047885 , -0.02559751,
          0.01856179,  0.5617469 ,  0.46149912]], dtype=float32)>,
 <tf.Variable 'lstm_cell_1/bias:0' shape=(8,) dtype=float32, numpy=array